name: themarkseddon
favicon: null
layout_spectrum: 0.312477963976562
typography_spectrum: 0.54798
title: themarkseddon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005049'
    - '#bbbdb2'
    - '#445e36'
    - '#329e87'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.41670895810239017
purpose: []
