name: tmark
favicon: null
layout_spectrum: 0.312477963976562
typography_spectrum: 0.36639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f7fb'
    - '#fc5c5e'
    - '#e5a727'
    - '#0a0813'
    - '#695cad'
  brandStrength: 0.8926665538456291
  lightness: 0.7020654487423599
  saturation: 0.9343453175388277
  rhythmicContrast: 0.41670895810239017
purpose: []
